### ISSUE TITLE
Broken builds - "ollama chat is damaged"

### ISSUE THREAD

**Issue by Thinkscape** [ollama-interface/Ollama-Gui#16]
Hey mates.

Just FYI, the github builds are failing, and producing broken releases.
This is what happens when trying to run it:

<img width="280" alt="image" src="https://github.com/ollama-interface/Ollama-Gui/assets/270528/21b2e8d5-8eec-499e-9355-ace2065b598c">

**Comment by fruchtzwerg** [comment]
This is a security feature on mac to prevent unsigned builds from executing and can be disabled with
`xattr -cr /Applications/Ollama\ Chat.app/`

**Comment by TwanLuttik** [comment]
Closing this issue since there is a beta release out.
