### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by hoseawu99** [ollama-interface/Ollama-Gui#20]
It seems that I can't build it on Windows.

**Comment by snatvb** [comment]
I will do in my fork soon: https://github.com/snatvb/Ollama-Gui

**Comment by snatvb** [comment]
UPD: you can take it 😉 https://github.com/snatvb/Ollama-Gui/releases/tag/v1.0.0

**Comment by TwanLuttik** [comment]
I'm closing this issue since a windows build will be available on the next beta release version
