### ISSUE TITLE
Build fails on M1 - Error beforeBuildCommand `pnpm build` failed with exit code 1

### ISSUE THREAD

**Issue by sethbang** [ollama-interface/Ollama-Gui#6]
Build command on Macbook M1 running MacOS 14.1 fails. Below is the terminal output.

➜  Ollama-Gui git:(main) ✗ pnpm build:app:silicon

> ollama-interface@0.0.0 build:app:silicon /Users/me/Code/Ollama-Gui
> tauri build --target aarch64-apple-darwin

     Running beforeBuildCommand `pnpm build`

> ollama-interface@0.0.0 build /Users/me/Code/Ollama-Gui
> tsc && vite build

src/components/ui/alert-dialog.tsx:12:3 - error TS2339: Property 'className' does not exist on type 'AlertDialogPortalProps'.

12   className,
     ~~~~~~~~~

src/components/ui/alert-dialog.tsx:15:32 - error TS2322: Type '{ children?: ReactNode; container?: HTMLElement | null | undefined; forceMount?: true | undefined; className: string; }' is not assignable to type 'IntrinsicAttributes & AlertDialogPortalProps'.
  Property 'className' does not exist on type 'IntrinsicAttributes & AlertDialogPortalProps'.

15   <AlertDialogPrimitive.Portal className={cn(className)} {...props} />
                                  ~~~~~~~~~

src/components/ui/dialog.tsx:12:3 - error TS2339: Property 'className' does not exist on type 'DialogPortalProps'.

12   className,
     ~~~~~~~~~

src/components/ui/dialog.tsx:15:27 - error TS2322: Type '{ children?: ReactNode; container?: HTMLElement | null | undefined; forceMount?: true | undefined; className: string; }' is not assignable to type 'IntrinsicAttributes & DialogPortalProps'.
  Property 'className' does not exist on type 'IntrinsicAttributes & DialogPortalProps'.

15   <DialogPrimitive.Portal className={cn(className)} {...props} />
                             ~~~~~~~~~

src/components/ui/sheet.tsx:15:3 - error TS2339: Property 'className' does not exist on type 'DialogPortalProps'.

15   className,
     ~~~~~~~~~

src/components/ui/sheet.tsx:18:26 - error TS2322: Type '{ children?: ReactNode; container?: HTMLElement | null | undefined; forceMount?: true | undefined; className: string; }' is not assignable to type 'IntrinsicAttributes & DialogPortalProps'.
  Property 'className' does not exist on type 'IntrinsicAttributes & DialogPortalProps'.

18   <SheetPrimitive.Portal className={cn(className)} {...props} />
                            ~~~~~~~~~

Found 6 errors in 3 files.

Errors  Files
     2  src/components/ui/alert-dialog.tsx:12
     2  src/components/ui/dialog.tsx:12
     2  src/components/ui/sheet.tsx:15
 ELIFECYCLE  Command failed with exit code 2.
       Error beforeBuildCommand `pnpm build` failed with exit code 1
 ELIFECYCLE  Command failed with exit code 1.

**Comment by TwanLuttik** [comment]
Its interesting its failing on building the vite part, maybe you could try again but i'm also improving the part for building on your machine which will come soon

**Comment by TwanLuttik** [comment]
@sethbang Workflow has been added so now you don't have to build it by your self, you can download it from [here](https://github.com/ollama-interface/Ollama-Gui/releases/tag/release-20231004235837)

**Comment by giacomorebonato** [comment]
I just built on M1 without issues

**Comment by TwanLuttik** [comment]
closing this due to the new beta release
