### ISSUE TITLE
it would be nice if you could insert a newline in the text box with shift+enter

### ISSUE THREAD

**Issue by jurb** [ollama-interface/Ollama-Gui#7]
Nice frontend! I think it would be nice if you could insert a newline in the text box with shift+enter.

**Comment by TwanLuttik** [comment]
I love that, definitely putting that on the list.

**Comment by TwanLuttik** [comment]
I have added support for multi line by shift enter a new line. These changes has been [merged](https://github.com/ollama-interface/Ollama-Gui/pull/10) to main

**Comment by jurb** [comment]
Great @TwanLuttik thank you!
